sudo: false
language: python
dist: trusty

jobs:
  fast_finish: true
  include:
    - python: 3.6
      env: TOXENV=py36-djmaster-postgres

    - stage: PyPI Release
      script: skip
      install: skip
      after_success: true
      deploy:
        provider: pypi
        user: blueyed
        password:
          secure: "DZz5qJMyXB/GVaT8dEpHnMjB+g+udbLSZfGl+g+Dr6B0iNEi9sSj1QEMSq9cLoPJJEJ/Q/LdpWGmVH6EGxKNVHRFS8xIdzaPSyGmMZD2qA6v7YSYrpXpdrFzqi9hFlY5MpVTrUoOo05AhgUEhFZvN1XM6z5tqCJtdMAHzNJfqNA="
        on:
          all_branches: true
        distributions: "sdist bdist_wheel"

  allow_failures:
    - env: TOXENV=py36-djmaster-postgres

install: true
script: true

after_success:
  - |
    set -ex
    if [[ "$PYTEST_DJANGO_COVERAGE" = 1 ]]; then
      pip install codecov

      coverage --version
      coverage combine
      coverage xml

      codecov_flags=${TOXENV//./}
      codecov_flags=${codecov_flags//-/ }
      codecov --required -X search gcov pycov -f coverage.xml --flags $codecov_flags
    fi
    set +x
